# Load balancer config (modified later by Module 4)
1.  events {}
2.  
3.  http {
4.      upstream app_backend {
5.          server app:5000;
6.      }
7.  
8.      server {
9.          listen 80;
10.         location / {
11.             proxy_pass http://app_backend;
12.         }
13.     }
14. }