groups:
  - name: sentinel_alerts
    rules:
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[1m]) * 100 > 10
        for: 10s
        annotations:
          summary: "Instance CPU is unusually high"